repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.6.8  # Check the latest version on Ruff GitHub page
    hooks:
      - id: ruff
        #args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Check the latest version on their GitHub page
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: pytest
      language: python
      types: [python]
      args: ["tests/"]
