version: '3'
services:
  neo4j:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: 'neo4j/test'
    ports:
      - "7687:7687"  # Bolt port for Neo4j connectivity
      - "7474:7474"  # HTTP interface
    volumes:
      - neo4j_data:/data
volumes:
  neo4j_data:
